title: mmmint.ai - building smart solutions
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
palette: blue
header:
  title: mmmint.ai
  logo_img: images/logo.png
  has_nav: true
  menu:
    actions:
      - label: Sign Up
        url: /signup
footer:
  logo_img: images/logo_alt.png
  tagline: mmmint.ai - building smart solutions
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; MMM Intelligence UG. All rights reserved."
  links:
    - text: Impressum
      url: "/impressum"
      new_window: false
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
